### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by sadoj-kuro** [Sn8ow/ViperX_TikTok#1]
always say solve the captcha and its already resolve

**Comment by Sn8ow** [comment]
this is a zefoy bug which is also without the program so you have to run ``` ViperX``` 2 times

**Comment by KuroSenseii** [comment]
zefoy is down 

502 Bad Gateway

**Comment by Sn8ow** [comment]
They're doing repairs 😕

**Comment by Sn8ow** [comment]
> zefoy is down
> 
> 502 Bad Gateway

try now

**Comment by KuroSenseii** [comment]
> > zefoy is down
> > 502 Bad Gateway
> 
> try now

dont working again 502 bad gateway

**Comment by Sn8ow** [comment]
![image](https://user-images.githubusercontent.com/80784394/146244247-c328f90e-9bdd-47ff-8814-7d24c2b568ec.png)
me working...

**Comment by Sn8ow** [comment]
> > > zefoy is down
> > > 502 Bad Gateway
> > 
> > 
> > try now
> 
> dont working again 502 bad gateway

try later

**Comment by KuroSenseii** [comment]
> 

Probably a blockage that affects me by mistake on their site, but as we can not contact them to do anything I think that will never be resolved for me

**Comment by Sn8ow** [comment]
> > 
> 
> Prawdopodobnie blokada, która wpływa na mnie przez pomyłkę na ich stronie, ale ponieważ nie możemy się z nimi skontaktować, aby cokolwiek zrobić, myślę, że nigdy nie zostanie to dla mnie rozwiązane

Try with VPN

**Comment by Sn8ow** [comment]
> > 
> 
> Probably a blockage that affects me by mistake on their site, but as we can not contact them to do anything I think that will never be resolved for me

Try with VPN

**Comment by KuroSenseii** [comment]
> > > 
> > 
> > 
> > Probably a blockage that affects me by mistake on their site, but as we can not contact them to do anything I think that will never be resolved for me
> 
> Try with VPN

same problem
